route:
  receiver: 'slack'

receivers:
  - name: 'slack'
       slack_configs:
          - send_resolved: true
             username: 'ruufman'
             channel: 'Tech-Training'
             api_url: 'tech-trainingteam.slack.com'
